title: プログラミングⅡ
author: Tatsuya Yatagawa
copyright: "CC BY-NC-SA 4.0, 2024"
# logo: 'qe-logo-large.png'

description: >-
  Pythonを用いて、ネットワークプログラミングの基礎について学ぶ

exclude_patterns:
  - _build
  - Thumbs.db
  - .DS_Store
  - .mypy_cache
  - .jupyter_cache
  - "**.ipynb_checkpoints"

only_build_toc_files: true

execute:
  allow_errors: false
  execute_notebooks: cache
  cache: ./.jupyter_cache
  timeout: 180

# HTML-specific settings
html:
  home_page_in_navbar: true
  use_multitoc_numbering: true
  use_repository_button: false
  use_issues_button: false

# Interact link settings
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: ""

# Launch button settings
repository:
  url: https://github.com/tatsy/1284-sds-programming-2
  path_to_book: ""
  branch: master

# Sphinx
sphinx:
  recursive_update: true
  config:
    language: ja
    # Syntax highlighting
    # pygments_style: friendly
    # MathJax
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # BibTeX
    bibtex_default_style: unsrt
    bibtex_reference_style: label
    # Disable download button
    html_theme_options:
      pygments_light_style: gotthard-light
      pygments_dark_style: material
      use_download_button: false

bibtex_bibfiles:
  - "references.bib"

# MyST options
parse:
  myst_footnote_transition: false
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence

# LaTeX
latex:
  latex_engine: "xelatex"
  use_jupyterbook_latex: true
